import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TranscriptEvent, UserMessageEvent } from "../models/Response";
import type { ChatSnapshot } from "../models/Chats";
import { chatSnapshotFixture } from "../models/chatSnapshotFixture";
import { countUserTurns, isFastModePromptOwed } from "./fast-mode-prompt";
import { getChatFastMode } from "../models/ModelSettings";
import { hasFastModePrompt } from "../models/HarnessCatalog";
import { isFastModePromptAnswered } from "../models/FastModePrompt";

vi.mock("../models/ModelSettings", () => ({ getChatFastMode: vi.fn() }));
vi.mock("../models/HarnessCatalog", () => ({ hasFastModePrompt: vi.fn() }));
vi.mock("../models/FastModePrompt", () => ({
  isFastModePromptAnswered: vi.fn(),
  openFastModePrompt: vi.fn(),
}));

const getChatFastModeMock = vi.mocked(getChatFastMode);
const hasFastModePromptMock = vi.mocked(hasFastModePrompt);
const isFastModePromptAnsweredMock = vi.mocked(isFastModePromptAnswered);

function userMsg(content: string, id: string, extra: Partial<UserMessageEvent> = {}): UserMessageEvent {
  return {
    timestamp: id,
    type: "user_message",
    event_id: id,
    source: "test",
    role: "user",
    content,
    ...extra,
  } as UserMessageEvent;
}

function assistantMsg(id: string): TranscriptEvent {
  return {
    timestamp: id,
    type: "assistant_message",
    event_id: id,
    source: "test",
    model: "m",
    text: "ok",
    tool_calls: [],
    stop_reason: null,
    usage: null,
    is_auth_error: false,
    is_api_error: false,
    api_error_kind: null,
    is_provider_fault: false,
  } as TranscriptEvent;
}

/** A conversation of `count` complete exchanges. */
function conversation(count: number): TranscriptEvent[] {
  const events: TranscriptEvent[] = [];
  for (let i = 0; i < count; i++) {
    events.push(userMsg(`question ${i}`, `u-${i}`));
    events.push(assistantMsg(`a-${i}`));
  }
  return events;
}

/** A first-labelled agent on a prompt-declaring harness -- the one the prompt is for. */
function firstAgent(labels: Record<string, string> = { first: "true" }): ChatSnapshot {
  return chatSnapshotFixture("agent-1", { name: "demo", labels, active_agent: { name: "demo", state: "started" } });
}

describe("countUserTurns", () => {
  it("counts the exchanges the user can actually see", () => {
    expect(countUserTurns(conversation(0))).toBe(0);
    expect(countUserTurns(conversation(3))).toBe(3);
  });

  it("ignores everything that is not the user taking a turn", () => {
    // The same messages the transcript view refuses to open a new turn for: the
    // seeded /welcome, the composer's own slash commands, framework injections,
    // stop-hook feedback, and permission verdicts the app injects.
    const events: TranscriptEvent[] = [
      userMsg("/welcome", "u-welcome", { display: "hidden" }),
      userMsg("/fast on", "u-fast", { display: "hidden" }),
      userMsg("/model sonnet", "u-model", { display: "hidden" }),
      userMsg("Caveat: the messages below were generated by the user", "u-meta", { display: "hidden" }),
      userMsg("Stop hook feedback:\nyou left changes uncommitted", "u-hook", {
        display: "chip",
        display_label: "Stop hook feedback",
      }),
      userMsg("Your permission request for Slack was granted for this session.", "u-perm", {
        display: "permission_resolution",
        resolution: "granted",
      }),
      userMsg("a real question", "u-real"),
      assistantMsg("a-real"),
    ];
    expect(countUserTurns(events)).toBe(1);
  });
});

describe("isFastModePromptOwed", () => {
  beforeEach(() => {
    hasFastModePromptMock.mockReturnValue(true);
    isFastModePromptAnsweredMock.mockReturnValue(false);
    getChatFastModeMock.mockReturnValue(true);
  });

  it("waits for the grace period to be used up", () => {
    expect(isFastModePromptOwed(firstAgent(), conversation(4), true)).toBe(false);
    expect(isFastModePromptOwed(firstAgent(), conversation(5), true)).toBe(true);
    expect(isFastModePromptOwed(firstAgent(), conversation(9), true)).toBe(true);
  });

  it("waits for the agent to finish replying", () => {
    expect(isFastModePromptOwed(firstAgent(), conversation(5), false)).toBe(false);
  });

  it("fires only for the first-labelled chat", () => {
    // Plain chats never launch fast, so the prompt would ask about a speed
    // nobody got; the first=true label scopes it to the one chat that did.
    expect(isFastModePromptOwed(firstAgent({}), conversation(9), true)).toBe(false);
    expect(isFastModePromptOwed(firstAgent({ first: "false" }), conversation(9), true)).toBe(false);
  });

  it("fires only when the harness declared the prompt", () => {
    hasFastModePromptMock.mockReturnValue(false);
    expect(isFastModePromptOwed(firstAgent(), conversation(9), true)).toBe(false);
  });

  it("never asks the same agent twice", () => {
    isFastModePromptAnsweredMock.mockReturnValue(true);
    expect(isFastModePromptOwed(firstAgent(), conversation(9), true)).toBe(false);
  });

  it("stays quiet when the user already turned fast mode off themselves", () => {
    getChatFastModeMock.mockReturnValue(false);
    expect(isFastModePromptOwed(firstAgent(), conversation(9), true)).toBe(false);
  });

  it("stays quiet for an unknown agent", () => {
    expect(isFastModePromptOwed(undefined, conversation(9), true)).toBe(false);
  });
});
