"""Chromium launch arguments for the browser fleet.

Ported from browser-use 0.13.1 (`browser_use/browser/profile.py`) when that dependency
was removed, and deliberately NOT re-derived from Playwright's own switch list.

The distinction matters and is easy to get backwards. Playwright's
`chromiumSwitches.ts` adds `--enable-automation` (which sets `navigator.webdriver = true`)
and `--disable-extensions` / `--disable-component-extensions-with-background-pages`
(which kill unpacked extensions on Chrome 145+). browser-use's list is a FORK of
Playwright's with exactly those removed -- see `_STRIPPED_FROM_PLAYWRIGHT` -- and that
subtraction is the thing the fleet actually needs: Fortress is a stealth build whose
entire point is not announcing itself, and the fleet loads unpacked extensions.

So this module is the curated list, kept as data. Anything added here should be checked
against those two constraints.
"""

# Feature names disabled as one `--disable-features=` argument (see LAUNCH_ARGS).
DISABLED_COMPONENTS = (
    'AcceptCHFrame',
    'AutoExpandDetailsElement',
    'AvoidUnnecessaryBeforeUnloadCheckSync',
    'CertificateTransparencyComponentUpdater',
    'DestroyProfileOnBrowserClose',
    'DialMediaRouteProvider',
    'ExtensionManifestV2Disabled',
    'GlobalMediaControls',
    'HttpsUpgrades',
    'ImprovedCookieControls',
    'LazyFrameLoading',
    'LensOverlay',
    'MediaRouter',
    'PaintHolding',
    'ThirdPartyStoragePartitioning',
    'Translate',
    'AutomationControlled',
    'BackForwardCache',
    'OptimizationHints',
    'ProcessPerSiteUpToMainFrameThreshold',
    'InterestFeedContentSuggestions',
    'CalculateNativeWinOcclusion',
    'HeavyAdPrivacyMitigations',
    'PrivacySandboxSettings4',
    'AutofillServerCommunication',
    'CrashReporting',
    'OverscrollHistoryNavigation',
    'InfiniteSessionRestore',
    'ExtensionDisableUnsupportedDeveloper',
    'ExtensionManifestV2Unsupported',
)

# Playwright default switches that must NEVER be emitted. Kept as data (rather than
# just "we don't add them") so the reason is greppable if someone reintroduces a
# Playwright-driven launch.
_STRIPPED_FROM_PLAYWRIGHT = (
    "--enable-automation",  # sets navigator.webdriver=true; defeats Fortress's whole purpose
    "--disable-extensions",  # the fleet loads uBlock / cookie-banner extensions unpacked
    "--disable-component-extensions-with-background-pages",  # kills unpacked extensions on Chrome 145+
    "--hide-scrollbars",  # scrollbars tell an agent there is more to scroll
)

_BASE_ARGS = (
    '--disable-field-trial-config',
    '--disable-background-networking',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-back-forward-cache',
    '--disable-breakpad',
    '--disable-client-side-phishing-detection',
    '--disable-component-update',
    '--no-default-browser-check',
    '--disable-dev-shm-usage',
    '--disable-hang-monitor',
    '--disable-ipc-flooding-protection',
    '--disable-popup-blocking',
    '--disable-prompt-on-repost',
    '--disable-renderer-backgrounding',
    '--metrics-recording-only',
    '--no-first-run',
    '--no-service-autorun',
    '--export-tagged-pdf',
    '--disable-search-engine-choice-screen',
    '--unsafely-disable-devtools-self-xss-warnings',
    '--enable-features=NetworkService,NetworkServiceInProcess',
    '--enable-network-information-downlink-max',
    '--disable-sync',
    '--allow-legacy-extension-manifests',
    '--allow-pre-commit-input',
    '--disable-blink-features=AutomationControlled',
    '--install-autogenerated-theme=0,0,0',
    '--log-level=2',
    '--disable-focus-on-load',
    '--disable-window-activation',
    '--generate-pdf-document-outline',
    '--no-pings',
    '--ash-no-nudges',
    '--disable-infobars',
    '--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
    '--hide-crash-restore-bubble',
    '--suppress-message-center-popups',
    '--disable-domain-reliability',
    '--disable-datasaver-prompt',
    '--disable-speech-synthesis-api',
    '--disable-speech-api',
    '--disable-print-preview',
    '--safebrowsing-disable-auto-update',
    '--disable-external-intent-requests',
    '--disable-desktop-notifications',
    '--noerrdialogs',
    '--silent-debugger-extension-api',
    '--disable-extensions-http-throttling',
    '--extensions-on-chrome-urls',
    '--disable-default-apps',
    '--disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DestroyProfileOnBrowserClose,DialMediaRouteProvider,ExtensionManifestV2Disabled,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate,AutomationControlled,BackForwardCache,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold,InterestFeedContentSuggestions,CalculateNativeWinOcclusion,HeavyAdPrivacyMitigations,PrivacySandboxSettings4,AutofillServerCommunication,CrashReporting,OverscrollHistoryNavigation,InfiniteSessionRestore,ExtensionDisableUnsupportedDeveloper,ExtensionManifestV2Unsupported',
)

# The fleet's own additions, on top of the ported list. These were already passed
# alongside browser-use's defaults, so they are part of the effective command line
# that runs today.
_FLEET_ARGS = (
    # Chromium blocklists --no-sandbox (which we must pass as root) and pins a permanent
    # "unsupported command-line flag" infobar above every page for it. We film Chrome's
    # real window, so the human would see that bar for the life of the browser.
    # --test-type is the only supported suppression that does not break stealth:
    # infobar_utils.cc skips the whole bad-flags prompt when it (or --enable-automation,
    # which is not an option here) is present. It disables Chrome's own background
    # *component* extensions; unpacked ones are unaffected, and page JS cannot see it.
    "--test-type",
    "--disable-gpu-compositing",
    "--disable-smooth-scrolling",
    "--wm-window-animations-disabled",
    "--force-prefers-reduced-motion",
    "--renderer-process-limit=4",
    "--no-first-run",
    "--disable-session-crashed-bubble",
    "--hide-crash-restore-bubble",
    "--disable-dev-shm-usage",
    # Maps the (0,0,w,h) capture region 1:1 to window pixels so the human's input
    # coordinates stay correct. Load-bearing for the streaming path.
    "--window-position=0,0",
    # Declare English explicitly rather than inheriting whatever locale the base image
    # happens to have. `--lang` sets Chrome's UI locale; `--accept-lang` sets the
    # Accept-Language header outright, so it does not matter whether LANG/LC_ALL are set
    # in the container at all.
    #
    # This fixes any site that honours Accept-Language. It does NOT fix Google, which
    # falls back to IP geolocation for its consent interstitial -- and our egress is an
    # OVH range that is physically in Oregon but carries French registration metadata
    # (RIPE lists 51.81.0.0/16 as non-RIPE-managed with country EU, and the org is OVH
    # SAS, Roubaix). For Google the lever is `hl=en` in the URL; see _HOME_URL.
    "--lang=en-US",
    "--accept-lang=en-US,en",
)


def launch_args(
    *,
    user_data_dir: str,
    remote_debugging_port: int = 0,
    window_size: "tuple[int, int] | None" = None,
    extensions: "tuple[str, ...]" = (),
    no_sandbox: bool = False,
) -> "list[str]":
    """The full Chromium argv (excluding the executable and the start URL).

    There is no viewport emulation here on purpose: the page must fill the real OS
    window so a pane resize reflows it, which is what browser-use's `no_viewport=True`
    bought. A fixed viewport would render at a constant size and letterbox the capture.
    """
    args = [
        *_BASE_ARGS,
        f"--disable-features={','.join(DISABLED_COMPONENTS)}",
        *_FLEET_ARGS,
        f"--user-data-dir={user_data_dir}",
        f"--remote-debugging-port={remote_debugging_port}",
    ]
    if window_size is not None:
        args.append(f"--window-size={window_size[0]},{window_size[1]}")
    if extensions:
        args.append(f"--load-extension={','.join(extensions)}")
    if no_sandbox:
        args.append("--no-sandbox")
    assert not (set(args) & set(_STRIPPED_FROM_PLAYWRIGHT)), "a Playwright anti-stealth switch leaked in"
    return args
