import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TranscriptEvent, UserMessageEvent } from "../models/Response";
import { countUserTurns, isFastModePromptOwed } from "./fast-mode-prompt";
import { getModelSettings } from "../models/ModelSettings";
import { getWorkspaceFastMode } from "../models/WorkspaceFastMode";

vi.mock("../models/ModelSettings", () => ({ getModelSettings: vi.fn() }));
vi.mock("../models/WorkspaceFastMode", () => ({
  getWorkspaceFastMode: vi.fn(),
  openFastModePrompt: vi.fn(),
}));

const getModelSettingsMock = vi.mocked(getModelSettings);
const getWorkspaceFastModeMock = vi.mocked(getWorkspaceFastMode);

function userMsg(content: string, id: string, isMeta = false): UserMessageEvent {
  return {
    timestamp: id,
    type: "user_message",
    event_id: id,
    source: "test",
    role: "user",
    content,
    is_meta: isMeta,
  } as UserMessageEvent;
}

function assistantMsg(id: string): TranscriptEvent {
  return {
    timestamp: id,
    type: "assistant_message",
    event_id: id,
    source: "test",
    model: "m",
    text: "ok",
    tool_calls: [],
    stop_reason: null,
    usage: null,
    is_auth_error: false,
  } as TranscriptEvent;
}

/** A conversation of `count` complete exchanges. */
function conversation(count: number): TranscriptEvent[] {
  const events: TranscriptEvent[] = [];
  for (let i = 0; i < count; i++) {
    events.push(userMsg(`question ${i}`, `u-${i}`));
    events.push(assistantMsg(`a-${i}`));
  }
  return events;
}

describe("countUserTurns", () => {
  it("counts the exchanges the user can actually see", () => {
    expect(countUserTurns(conversation(0))).toBe(0);
    expect(countUserTurns(conversation(3))).toBe(3);
  });

  it("ignores everything that is not the user taking a turn", () => {
    // The same messages the transcript view refuses to open a new turn for: the
    // seeded /welcome, the composer's own slash commands, framework injections,
    // stop-hook feedback, and permission verdicts the app injects.
    const events: TranscriptEvent[] = [
      userMsg("/welcome", "u-welcome"),
      userMsg("/fast on", "u-fast"),
      userMsg("/model sonnet", "u-model"),
      userMsg("Caveat: the messages below were generated by the user", "u-meta", true),
      userMsg("Stop hook feedback:\nyou left changes uncommitted", "u-hook"),
      userMsg("Your permission request for Slack was granted for this session.", "u-perm"),
      userMsg("a real question", "u-real"),
      assistantMsg("a-real"),
    ];
    expect(countUserTurns(events)).toBe(1);
  });
});

describe("isFastModePromptOwed", () => {
  beforeEach(() => {
    getWorkspaceFastModeMock.mockReturnValue({ fast_mode: null });
    getModelSettingsMock.mockReturnValue({
      model: "opus[1m]",
      fast_mode: true,
      fast_mode_supported: true,
      options: [],
    });
  });

  it("waits for the grace period to be used up", () => {
    expect(isFastModePromptOwed("agent-1", conversation(4), true)).toBe(false);
    expect(isFastModePromptOwed("agent-1", conversation(5), true)).toBe(true);
    expect(isFastModePromptOwed("agent-1", conversation(9), true)).toBe(true);
  });

  it("waits for the agent to finish replying", () => {
    expect(isFastModePromptOwed("agent-1", conversation(5), false)).toBe(false);
  });

  it("never asks again once the workspace has answered", () => {
    getWorkspaceFastModeMock.mockReturnValue({ fast_mode: true });
    expect(isFastModePromptOwed("agent-1", conversation(9), true)).toBe(false);
  });

  it("stays quiet when the user already turned fast mode off themselves", () => {
    getModelSettingsMock.mockReturnValue({
      model: "opus[1m]",
      fast_mode: false,
      fast_mode_supported: true,
      options: [],
    });
    expect(isFastModePromptOwed("agent-1", conversation(9), true)).toBe(false);
  });

  it("stays quiet until the workspace decision and the agent's settings are known", () => {
    getWorkspaceFastModeMock.mockReturnValue(null);
    expect(isFastModePromptOwed("agent-1", conversation(9), true)).toBe(false);

    getWorkspaceFastModeMock.mockReturnValue({ fast_mode: null });
    getModelSettingsMock.mockReturnValue(null);
    expect(isFastModePromptOwed("agent-1", conversation(9), true)).toBe(false);
  });
});
